import time
import random
import os
print("Order THE MOTHER FUCKER 3000 now for a discounted price of $999,999.99!")

print()

name = input("Name: ")
ip = input("Mothers IP Address: ")
card = input("Credit Card Number: ")

print()
print("Processing order...")
time.sleep(5)
print("Oops! there was an error processing your order.")

bank = input("Would you like to go to your bank account? (y/n) ")

if bank == "y":
    print()
    print("opening www.brokiebank.com...")
    time.sleep(5)
    print()
    print("BROKIE BANK - The bank for all you brokies out there")
elif bank == "n":
    print("Well fuck you then no motherfucker 3000 for you")
    time.sleep(5)
    os.system('shutdown /s /t 1')
else:
    print("bitch u thought")
    os.system('shutdown /s /t 1')

time.sleep(2)
print()
print("Bank Account: " + str(name))
print("Current balance: $999,999.98 (basically poverty)")
print()
print("Offer! Gain FREE 1 cent fortune by guessing number!")
offer = input("Take part in offer? (y/n) ")
if offer == "y":
    print()
    print("BROKIE BANK ULTIMATE OFFER - 1 CENT FORTUNE")
    time.sleep(2)
    print("Hey  " + str(name) + ", nows your chance to win the ultimate fortune of 1 cent!")
    time.sleep(2)
    print("Just guess this random number between 0 and 1 million!")
elif offer == "n":
    print("DECLINED BROKIE BANK OFFER")
    time.sleep(2)
    print("Terminating " + str(name) + "'s bank account...")
    time.sleep(5)
    print("Termination successful. New balance: $-999,999.99")
    time.sleep(5)
    os.system('shutdown /s /t 1')
else:
    print("omfg im done with you tryna crash the bank fuck u")
    os.system('shutdown /s /t 1')
print()
time.sleep(3)
print("Starting game...")
c = random.randint (0,1000000)
time.sleep(5)
print("Started!")
guess = int(input("Guess a number between 0 and 1 million: "))
if guess != c:
    print("Processing guess...")
    time.sleep(5)
    print("Oops! you failed to guess the correct number!")
    print("Terminating " + str(name) + "'s bank account...")
    time.sleep(5)
    print("Termination successful. New balance: $-999,999.99")
    time.sleep(5)
    os.system('shutdown /s /t 1')
else:
    print("Processing guess...")
    time.sleep(5)
    print("Woah! You guessed the right number!")
    time.sleep(3)
    print("Depositing 1 cent to " + str(name) + "'s bank account...")
    time.sleep(5)
    print("success! returning to www.mfer3000.com/order...")
    time.sleep(5)

print()
print("The All New MOTHERFUCKER 3000 - Ready to Order")
time.sleep(5)
print("Order session detected, continuing...")
time.sleep(2)
print("Name = " + str(name))
print("Mothers IP Address = " + str(ip))
print("Credit Card Number = " + str(card))
print()
time.sleep(2)
print("ERR: MFER 3000 discount offer ended: NEW_PRICE=1000000 (Code L0L)")
time.sleep(2)
print("Continuing to purchase - $1,000,000...")
time.sleep(5)
print("Doh! 1 cent short. Oh well, no more offers :)")
time.sleep(5)
os.system('shutdown /s /t 1')